services:
  sms-api:
    image: "sms-api"
    build: .
    container_name: sms-api
    ports:
      - 16800:9090
    volumes:
      - F:/Sem Sopanha/Spring Framework/BankSystem/File Server/:/File Server/
    networks:
      - sms-net
    restart: always
    depends_on:
      -  sms-db

  sms-db:
    image: postgres:16.3-bullseye
    container_name: con-sms-db
    ports:
      - 4441:5432
    environment:
      POSTGRES_PASSWORD: sms@2024
      POSTGRES_USER: sms
      POSTGRES_DB: sms_db
    volumes:
      - sms-vol:/var/lib/postgresql/data
    networks:
      - sms-net

volumes:
  sms-vol:

networks:
  sms-net:
    driver: bridge